@startuml
start
:传入头结点和目标结点的位置;
if (链表是否为空\n位置是否合法？) then (yes)
    :退出程序;
    stop
else (no)
    :临时创建一个结点用于\n继承当前到达的结点的父结点;
    :从头结点开始逐级遍历;
    :到达目标位置;
    :使父结点指向当前结点的子结点;
    :释放当前结点;
    stop
endif
@enduml