# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Asus/Documents/GitHub/COD_labs/_lab5/src/_lab5/_lab5.srcs/sources_1/ip/INS_MEM_1/INS_MEM_1.xci
# IP: The module: 'INS_MEM_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/Documents/GitHub/COD_labs/_lab5/src/_lab5/_lab5.srcs/sources_1/ip/INS_MEM_1/INS_MEM_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INS_MEM_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Asus/Documents/GitHub/COD_labs/_lab5/src/_lab5/_lab5.srcs/sources_1/ip/INS_MEM_1/INS_MEM_1.xci
# IP: The module: 'INS_MEM_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/Documents/GitHub/COD_labs/_lab5/src/_lab5/_lab5.srcs/sources_1/ip/INS_MEM_1/INS_MEM_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INS_MEM_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
