# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Sources/Nexys4DDR_Master.xdc

# XDC: imports/sources_1/FPGAOL.xdc

# IP: ip/instruction_mem/instruction_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==instruction_mem || ORIG_REF_NAME==instruction_mem} -quiet] -quiet
