# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/CODexp/Lab5/CPU5/CPU5.runs/synth_1/Run_ol.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/CODexp/Lab5/CPU5/CPU5.cache/wt [current_project]
set_property parent.project_path C:/CODexp/Lab5/CPU5/CPU5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/CODexp/Lab5/CPU5/CPU5.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/instruction_mem/inst.coe
add_files C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/instruction_mem/inst3.coe
add_files C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/instruction_mem/lab4.coe
add_files C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/data_mem/data.coe
add_files C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/instruction_mem/hazards_test.coe
read_verilog -library xil_defaultlib {
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/imports/new/ALU.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/CPU.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/Control.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/EXMEM.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/Forwarding.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/Hazard.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/IDEX.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/IFID.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/imports/new/ImmGen.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/MEMWB.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/imports/new/Registers.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/WBIF.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/new/pdu.v
  C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/Run_ol.v
}
read_ip -quiet C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/instruction_mem/instruction_mem.xci
set_property used_in_implementation false [get_files -all c:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/instruction_mem/instruction_mem_ooc.xdc]

read_ip -quiet C:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/data_mem/data_mem.xci
set_property used_in_implementation false [get_files -all c:/CODexp/Lab5/CPU5/CPU5.srcs/sources_1/ip/data_mem/data_mem_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/CODexp/Lab5/CPU5/CPU5.srcs/constrs_1/imports/Sources/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files C:/CODexp/Lab5/CPU5/CPU5.srcs/constrs_1/imports/Sources/Nexys4DDR_Master.xdc]

read_xdc C:/CODexp/Lab5/CPU5/CPU5.srcs/constrs_1/imports/sources_1/FPGAOL.xdc
set_property used_in_implementation false [get_files C:/CODexp/Lab5/CPU5/CPU5.srcs/constrs_1/imports/sources_1/FPGAOL.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Run_ol -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Run_ol.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Run_ol_utilization_synth.rpt -pb Run_ol_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
