# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Asus/Documents/GitHub/COD_labs/_lab3/src/_lab3/_lab3.srcs/sources_1/ip/ins_a/ins_a.xci
# IP: The module: 'ins_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/Documents/GitHub/COD_labs/_lab3/src/_lab3/_lab3.srcs/sources_1/ip/ins_a/ins_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ins_a'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Asus/Documents/GitHub/COD_labs/_lab3/src/_lab3/_lab3.srcs/sources_1/ip/ins_a/ins_a.xci
# IP: The module: 'ins_a' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/Documents/GitHub/COD_labs/_lab3/src/_lab3/_lab3.srcs/sources_1/ip/ins_a/ins_a_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ins_a'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
