# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Asus/Documents/GitHub/COD_labs/_lab3/src/_lab3/_lab3.srcs/sources_1/ip/data/data.xci
# IP: The module: 'data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/Documents/GitHub/COD_labs/_lab3/src/_lab3/_lab3.srcs/sources_1/ip/data/data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Asus/Documents/GitHub/COD_labs/_lab3/src/_lab3/_lab3.srcs/sources_1/ip/data/data.xci
# IP: The module: 'data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Asus/Documents/GitHub/COD_labs/_lab3/src/_lab3/_lab3.srcs/sources_1/ip/data/data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
