# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/CODexp/Lab4/CPU/CPU.srcs/sources_1/ip/Data_memory/Data_memory.xci
# IP: The module: 'Data_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CODexp/Lab4/CPU/CPU.srcs/sources_1/ip/Data_memory/Data_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/CODexp/Lab4/CPU/CPU.srcs/sources_1/ip/Data_memory/Data_memory.xci
# IP: The module: 'Data_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/CODexp/Lab4/CPU/CPU.srcs/sources_1/ip/Data_memory/Data_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Data_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
